import { useNavigate, useParams } from "react-router";
import { useState } from "react";
import {
  ArrowLeft,
  User,
  MapPin,
  Calendar,
  Package,
  FileText,
  Scale,
  Sparkles,
  Check,
  Edit3,
  AlertTriangle,
  ShieldCheck,
  Download,
  Send,
} from "lucide-react";

// Mock structured data — real mein ye backend/AI se aayega
const mockComplaint = {
  id: "CMP12345",
  incidentType: "Theft",
  description:
    "Complainant reported that their mobile phone (iPhone 14) was stolen while boarding the evening metro at Rajiv Chowk station around 6:30 PM. The complainant noticed the phone missing shortly after and suspects it was taken during the crowded boarding process.",
  date: "17 May 2026",
  time: "18:30",
  location: "Rajiv Chowk Metro Station, New Delhi",
  complainant: { name: "Priya Sharma", contact: "+91 98765 43210", address: "Rajiv Chowk, New Delhi" },
  evidence: ["metro_ticket.jpg", "phone_invoice.pdf"],
  riskLevel: "Medium",
};

const suggestedSections = [
  {
    section: "IPC Section 379",
    title: "Theft",
    confidence: 92,
    reasoning: "Complaint describes removal of movable property (mobile phone) without consent, fitting the core definition of theft under IPC 379.",
  },
  {
    section: "IPC Section 356",
    title: "Assault or use of criminal force in attempt to commit theft",
    confidence: 41,
    reasoning: "Low confidence — no indication of physical force or assault was used during the incident based on complainant's statement.",
  },
];

const riskStyles: Record<string, string> = {
  High: "bg-red-100 text-red-700",
  Medium: "bg-amber-100 text-amber-700",
  Low: "bg-green-100 text-green-700",
};

export default function ComplaintDetail() {
  const navigate = useNavigate();
  const { id } = useParams();

  const [activeTab, setActiveTab] = useState<"structured" | "legal" | "draft">("structured");
  const [acceptedSections, setAcceptedSections] = useState<string[]>(["IPC Section 379"]);
  const [firDraft, setFirDraft] = useState(
    `FIRST INFORMATION REPORT\n\nComplaint ID: ${mockComplaint.id}\nDate of Incident: ${mockComplaint.date}, ${mockComplaint.time}\nPlace of Occurrence: ${mockComplaint.location}\n\nComplainant: ${mockComplaint.complainant.name}\nContact: ${mockComplaint.complainant.contact}\n\nBrief Facts of the Case:\n${mockComplaint.description}\n\nApplicable Sections: IPC 379 (Theft)\n\nThis FIR draft has been auto-generated by NyayaySetu AI and requires officer verification before registration.`
  );

  const toggleSection = (section: string) => {
    setAcceptedSections((prev) =>
      prev.includes(section) ? prev.filter((s) => s !== section) : [...prev, section]
    );
  };

  return (
    <div className="min-h-screen bg-slate-100 px-4 py-8">
      <div className="w-full max-w-5xl mx-auto">
        <button
          onClick={() => navigate("/police/complaints")}
          className="flex items-center gap-2 text-slate-500 hover:text-slate-800 mb-5 text-sm font-medium cursor-pointer"
        >
          <ArrowLeft size={18} />
          Back to complaints
        </button>

        {/* Header card */}
        <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-5 shadow-xs">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
            <div>
              <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">
                Complaint Review
              </p>
              <h1 className="text-2xl font-bold text-slate-900 font-mono">{id ?? mockComplaint.id}</h1>
            </div>
            <span className={`text-xs font-semibold px-3 py-1.5 rounded-full flex items-center gap-1.5 ${riskStyles[mockComplaint.riskLevel]}`}>
              <AlertTriangle size={13} />
              {mockComplaint.riskLevel} Risk
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm bg-slate-50 rounded-xl p-4">
            <div className="flex items-start gap-2">
              <User size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">Complainant</p>
                <p className="font-medium text-slate-800">{mockComplaint.complainant.name}</p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Calendar size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">Date & Time</p>
                <p className="font-medium text-slate-800">{mockComplaint.date}, {mockComplaint.time}</p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <MapPin size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">Location</p>
                <p className="font-medium text-slate-800">{mockComplaint.location}</p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Package size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">Evidence</p>
                <p className="font-medium text-slate-800">{mockComplaint.evidence.length} file(s) attached</p>
              </div>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex bg-white border border-slate-200 rounded-xl p-1.5 mb-5 shadow-xs">
          {[
            { key: "structured", label: "Complaint Structuring", icon: FileText },
            { key: "legal", label: "Legal Section Assistance", icon: Scale },
            { key: "draft", label: "FIR Draft", icon: Sparkles },
          ].map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as typeof activeTab)}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-semibold rounded-lg transition cursor-pointer ${
                activeTab === tab.key ? "bg-blue-950 text-white" : "text-slate-500 hover:bg-slate-50"
              }`}
            >
              <tab.icon size={15} />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab: Complaint Structuring */}
        {activeTab === "structured" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-slate-900">AI-Structured Complaint Data</h2>
              <button className="text-xs font-semibold text-blue-800 flex items-center gap-1 cursor-pointer">
                <Edit3 size={13} />
                Edit
              </button>
            </div>
            <div className="space-y-4 text-sm">
              <div>
                <p className="text-xs text-slate-400 mb-1">Incident Type</p>
                <p className="font-medium text-slate-800">{mockComplaint.incidentType}</p>
              </div>
              <div>
                <p className="text-xs text-slate-400 mb-1">Description (Original Statement)</p>
                <p className="text-slate-700 leading-relaxed bg-slate-50 rounded-lg p-3 border border-slate-100">
                  {mockComplaint.description}
                </p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-slate-400 mb-1">Complainant Contact</p>
                  <p className="font-medium text-slate-800">{mockComplaint.complainant.contact}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-400 mb-1">Address</p>
                  <p className="font-medium text-slate-800">{mockComplaint.complainant.address}</p>
                </div>
              </div>
              <div>
                <p className="text-xs text-slate-400 mb-1">Attached Evidence</p>
                <div className="flex flex-wrap gap-2">
                  {mockComplaint.evidence.map((f) => (
                    <span key={f} className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1.5 rounded-md border border-slate-200">
                      📎 {f}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab: Legal Section Assistance */}
        {activeTab === "legal" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <h2 className="font-bold text-slate-900 mb-1">AI-Suggested Legal Sections</h2>
            <p className="text-xs text-slate-500 mb-5">
              Review each suggestion and accept the ones applicable to this case.
            </p>
            <div className="space-y-3">
              {suggestedSections.map((s) => {
                const accepted = acceptedSections.includes(s.section);
                return (
                  <div
                    key={s.section}
                    className={`border rounded-xl p-4 transition ${
                      accepted ? "border-blue-700 bg-blue-50/40" : "border-slate-200"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div>
                        <p className="font-bold text-slate-900 text-sm">{s.section}</p>
                        <p className="text-xs text-slate-500">{s.title}</p>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <span className="text-xs font-semibold text-slate-500">{s.confidence}% match</span>
                        <button
                          onClick={() => toggleSection(s.section)}
                          className={`w-7 h-7 rounded-full flex items-center justify-center transition cursor-pointer ${
                            accepted ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-400"
                          }`}
                        >
                          <Check size={14} strokeWidth={3} />
                        </button>
                      </div>
                    </div>
                    <p className="text-xs text-slate-500 leading-relaxed">{s.reasoning}</p>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Tab: FIR Draft */}
        {activeTab === "draft" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h2 className="font-bold text-slate-900">AI-Generated FIR Draft</h2>
                <p className="text-xs text-slate-500">Editable — verify all details before finalizing.</p>
              </div>
              <button className="text-xs font-semibold text-slate-600 flex items-center gap-1.5 border border-slate-300 rounded-lg px-3 py-1.5 cursor-pointer">
                <Download size={13} />
                Export PDF
              </button>
            </div>
            <textarea
              value={firDraft}
              onChange={(e) => setFirDraft(e.target.value)}
              rows={16}
              className="w-full border border-slate-300 rounded-xl px-4 py-3 text-sm font-mono leading-relaxed focus:outline-none focus:ring-2 focus:ring-blue-700 resize-none"
            />

            <div className="flex flex-col sm:flex-row gap-3 mt-5">
              <button className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl py-3 text-sm font-semibold transition cursor-pointer">
                Save as Draft
              </button>
              <button className="flex-1 bg-blue-950 hover:bg-blue-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer">
                <ShieldCheck size={16} />
                Verify & Register FIR
              </button>
              <button className="flex-1 bg-green-800 hover:bg-green-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer">
                <Send size={16} />
                Notify Complainant
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}