// import { useNavigate, useParams } from "react-router";
// import { useState, useEffect } from "react";
// import {
//   ArrowLeft,
//   User,
//   MapPin,
//   Calendar,
//   Package,
//   FileText,
//   Scale,
//   Sparkles,
//   Check,
//   ShieldCheck,
//   RefreshCw,
//   CheckCircle2,
//   AlertCircle,
// } from "lucide-react";
// import {
//   fetchComplaintById,
//   updateComplaintStatusApi,
//   type Complaint,
// } from "../../services/api";

// const statusStyles: Record<string, string> = {
//   SUBMITTED: "bg-slate-100 text-slate-700 border-slate-200",
//   Submitted: "bg-slate-100 text-slate-700 border-slate-200",
//   UNDER_REVIEW: "bg-blue-100 text-blue-800 border-blue-200",
//   "Under Review": "bg-blue-100 text-blue-800 border-blue-200",
//   INVESTIGATING: "bg-blue-100 text-blue-800 border-blue-200",
//   ASSIGNED: "bg-blue-100 text-blue-800 border-blue-200",
//   FIR_DRAFT_GENERATED: "bg-amber-100 text-amber-800 border-amber-200",
//   "FIR Drafted": "bg-amber-100 text-amber-800 border-amber-200",
//   "FIR Draft Generated": "bg-amber-100 text-amber-800 border-amber-200",
//   OFFICER_VERIFICATION: "bg-orange-100 text-orange-800 border-orange-200",
//   "Officer Verification": "bg-orange-100 text-orange-800 border-orange-200",
//   FIR_REGISTERED: "bg-green-100 text-green-800 border-green-200",
//   "FIR Registered": "bg-green-100 text-green-800 border-green-200",
//   CLOSED: "bg-emerald-100 text-emerald-800 border-emerald-200",
//   Closed: "bg-emerald-100 text-emerald-800 border-emerald-200",
//   RESOLVED: "bg-emerald-100 text-emerald-800 border-emerald-200",
// };

// export default function ComplaintDetail() {
//   const navigate = useNavigate();
//   const { id } = useParams<{ id: string }>();

//   const [complaint, setComplaint] = useState<Complaint | null>(null);
//   const [loading, setLoading] = useState(true);
//   const [error, setError] = useState<string | null>(null);
//   const [successMessage, setSuccessMessage] = useState<string | null>(null);
//   const [updatingStatus, setUpdatingStatus] = useState(false);

//   const [activeTab, setActiveTab] = useState<"structured" | "legal" | "draft">("structured");
//   const [acceptedSections, setAcceptedSections] = useState<string[]>(["IPC Section 379 / BNS 303"]);
//   const [firDraft, setFirDraft] = useState("");

//   const loadComplaint = async () => {
//     if (!id) return;
//     setLoading(true);
//     setError(null);
//     try {
//       const res = await fetchComplaintById(id);
//       if (res.complaint) {
//         setComplaint(res.complaint);
//         const c = res.complaint;
//         const complainantName =
//           c.victimName ||
//           c.victim?.name ||
//           (c.user && typeof c.user === "object" ? c.user.name : "Complainant");
//         const complainantContact =
//           c.victim?.contact ||
//           c.victim?.phone ||
//           (c.user && typeof c.user === "object" ? c.user.phone : "Not provided");

//         setFirDraft(
//           `FIRST INFORMATION REPORT\n\nComplaint ID: ${c.complaintId}\nDate of Incident: ${c.date || "Unspecified"}, Time: ${c.time || "Unspecified"}\nPlace of Occurrence: ${c.location || "Unspecified"}\n\nComplainant: ${complainantName}\nContact: ${complainantContact}\n\nIncident Category: ${c.incidentType || "General Incident"}\n\nBrief Facts of the Case:\n${c.description || "No statement recorded."}\n\nApplicable Legal Sections:\n- IPC Section 379 / Bharatiya Nyaya Sanhita (BNS)\n\nStatus: ${c.status}\n\nThis FIR draft has been auto-generated by NyayaySetu AI and verified by Delhi Police.`
//         );
//       }
//     } catch (err: any) {
//       console.error("Error loading complaint:", err);
//       setError(err?.message || "Failed to load complaint from database.");
//     } finally {
//       setLoading(false);
//     }
//   };

//   useEffect(() => {
//     loadComplaint();
//   }, [id]);

//   const handleStatusChange = async (newStatus: string) => {
//     if (!id) return;
//     setUpdatingStatus(true);
//     setError(null);
//     setSuccessMessage(null);
//     try {
//       const res = await updateComplaintStatusApi(id, newStatus);
//       if (res.complaint) {
//         setComplaint(res.complaint);
//         setSuccessMessage(`Complaint status updated successfully to ${newStatus.replace(/_/g, " ")}.`);
//         setTimeout(() => setSuccessMessage(null), 4000);
//       }
//     } catch (err: any) {
//       console.error("Failed to update status:", err);
//       setError(err?.message || "Failed to update complaint status.");
//     } finally {
//       setUpdatingStatus(false);
//     }
//   };

//   const toggleSection = (section: string) => {
//     setAcceptedSections((prev) =>
//       prev.includes(section) ? prev.filter((s) => s !== section) : [...prev, section]
//     );
//   };

//   if (loading && !complaint) {
//     return (
//       <div className="min-h-screen bg-slate-100 flex items-center justify-center p-4">
//         <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center shadow-xs">
//           <RefreshCw className="animate-spin text-blue-800 mx-auto mb-3" size={28} />
//           <p className="text-sm font-semibold text-slate-700">Loading complaint record from database...</p>
//         </div>
//       </div>
//     );
//   }

//   const complainantName =
//     complaint?.victimName ||
//     complaint?.victim?.name ||
//     (complaint?.user && typeof complaint.user === "object" ? complaint.user.name : null) ||
//     "Citizen Complainant";
//   const complainantContact =
//     complaint?.victim?.contact ||
//     complaint?.victim?.phone ||
//     (complaint?.user && typeof complaint.user === "object" ? complaint.user.phone : null) ||
//     "Not provided";
//   const complainantEmail =
//     (complaint?.user && typeof complaint.user === "object" ? complaint.user.email : null) ||
//     complaint?.victim?.email ||
//     "Not provided";
//   const displayDate =
//     complaint?.date ||
//     (complaint?.createdAt
//       ? new Date(complaint.createdAt).toLocaleDateString("en-IN", {
//           day: "numeric",
//           month: "short",
//           year: "numeric",
//         })
//       : "Not specified");

//   const suggestedSections = [
//     {
//       section: "IPC Section 379 / BNS Section 303",
//       title: "Theft",
//       confidence: 94,
//       reasoning: `Complaint describes incident categorized as ${complaint?.incidentType || "theft"}, involving movable property taken without consent.`,
//     },
//     {
//       section: "IPC Section 356 / BNS Section 304",
//       title: "Assault or use of criminal force in attempt to commit theft",
//       confidence: 65,
//       reasoning: "Applicable if physical confrontation or snatching occurred during the incident.",
//     },
//   ];

//   return (
//     <div className="min-h-screen bg-slate-100 px-4 py-8">
//       <div className="w-full max-w-5xl mx-auto">
//         <div className="flex items-center justify-between mb-5">
//           <button
//             onClick={() => navigate("/police/complaints")}
//             className="flex items-center gap-2 text-slate-500 hover:text-slate-800 text-sm font-medium transition cursor-pointer"
//           >
//             <ArrowLeft size={18} />
//             Back to complaints
//           </button>
//           <button
//             onClick={loadComplaint}
//             title="Refresh record"
//             className="flex items-center gap-1.5 text-xs text-slate-600 bg-white border border-slate-300 rounded-lg px-3 py-1.5 shadow-xs hover:bg-slate-50 transition cursor-pointer"
//           >
//             <RefreshCw size={13} className={loading ? "animate-spin" : ""} />
//             Refresh
//           </button>
//         </div>

//         {/* Feedback banners */}
//         {successMessage && (
//           <div className="bg-green-50 border border-green-200 text-green-800 text-xs rounded-xl p-3.5 mb-4 flex items-center gap-2 shadow-xs">
//             <CheckCircle2 size={16} className="flex-shrink-0 text-green-600" />
//             <span className="font-medium">{successMessage}</span>
//           </div>
//         )}
//         {error && (
//           <div className="bg-red-50 border border-red-200 text-red-800 text-xs rounded-xl p-3.5 mb-4 flex items-center gap-2 shadow-xs">
//             <AlertCircle size={16} className="flex-shrink-0 text-red-600" />
//             <span className="font-medium">{error}</span>
//           </div>
//         )}

//         {/* Header card with status changer */}
//         <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-5 shadow-xs">
//           <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-5 pb-4 border-b border-slate-100">
//             <div>
//               <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">
//                 Police Complaint & FIR Review
//               </p>
//               <h1 className="text-2xl font-bold text-slate-900 font-mono mt-0.5">
//                 {complaint?.complaintId || id}
//               </h1>
//             </div>

//             {/* Status Control */}
//             <div className="flex items-center gap-3 bg-slate-50 p-2.5 rounded-xl border border-slate-200">
//               <span className="text-xs font-semibold text-slate-600">Status:</span>
//               <select
//                 value={complaint?.status || "SUBMITTED"}
//                 onChange={(e) => handleStatusChange(e.target.value)}
//                 disabled={updatingStatus}
//                 className="border border-slate-300 rounded-lg px-3 py-1.5 text-xs font-bold text-slate-800 bg-white focus:ring-2 focus:ring-blue-700 outline-none cursor-pointer"
//               >
//                 <option value="SUBMITTED">Submitted</option>
//                 <option value="UNDER_REVIEW">Under Review</option>
//                 <option value="FIR_DRAFT_GENERATED">FIR Drafted</option>
//                 <option value="OFFICER_VERIFICATION">Officer Verification</option>
//                 <option value="FIR_REGISTERED">FIR Registered</option>
//                 <option value="CLOSED">Closed</option>
//               </select>
//               <span
//                 className={`text-[11px] font-bold px-2.5 py-1 rounded-full border ${
//                   statusStyles[complaint?.status || "SUBMITTED"] || "bg-slate-100 text-slate-700"
//                 }`}
//               >
//                 {(complaint?.status || "SUBMITTED").replace(/_/g, " ")}
//               </span>
//             </div>
//           </div>

//           <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-sm bg-slate-50 rounded-xl p-4">
//             <div className="flex items-start gap-2">
//               <User size={15} className="text-slate-400 mt-0.5" />
//               <div>
//                 <p className="text-xs text-slate-400">Complainant</p>
//                 <p className="font-medium text-slate-800">{complainantName}</p>
//                 <p className="text-[11px] text-slate-500">{complainantContact}</p>
//               </div>
//             </div>
//             <div className="flex items-start gap-2">
//               <Calendar size={15} className="text-slate-400 mt-0.5" />
//               <div>
//                 <p className="text-xs text-slate-400">Date & Time</p>
//                 <p className="font-medium text-slate-800">
//                   {displayDate}
//                   {complaint?.time ? `, ${complaint.time}` : ""}
//                 </p>
//               </div>
//             </div>
//             <div className="flex items-start gap-2">
//               <MapPin size={15} className="text-slate-400 mt-0.5" />
//               <div>
//                 <p className="text-xs text-slate-400">Location</p>
//                 <p className="font-medium text-slate-800">{complaint?.location || "Delhi"}</p>
//               </div>
//             </div>
//             <div className="flex items-start gap-2">
//               <Package size={15} className="text-slate-400 mt-0.5" />
//               <div>
//                 <p className="text-xs text-slate-400">Category & Property</p>
//                 <p className="font-medium text-slate-800 capitalize">
//                   {complaint?.incidentType || "General Incident"}
//                 </p>
//                 {complaint?.stolenItem && (
//                   <p className="text-[11px] text-slate-500">Item: {complaint.stolenItem}</p>
//                 )}
//               </div>
//             </div>
//           </div>
//         </div>

//         {/* Tabs */}
//         <div className="flex bg-white border border-slate-200 rounded-xl p-1.5 mb-5 shadow-xs">
//           {[
//             { key: "structured", label: "Complaint Structuring", icon: FileText },
//             { key: "legal", label: "Legal Section Assistance", icon: Scale },
//             { key: "draft", label: "FIR Draft", icon: Sparkles },
//           ].map((tab) => (
//             <button
//               key={tab.key}
//               onClick={() => setActiveTab(tab.key as typeof activeTab)}
//               className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-semibold rounded-lg transition cursor-pointer ${
//                 activeTab === tab.key ? "bg-blue-950 text-white" : "text-slate-500 hover:bg-slate-50"
//               }`}
//             >
//               <tab.icon size={15} />
//               {tab.label}
//             </button>
//           ))}
//         </div>

//         {/* Tab: Complaint Structuring */}
//         {activeTab === "structured" && (
//           <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
//             <h2 className="font-bold text-slate-900 mb-4">AI-Structured Complaint Details</h2>
//             <div className="space-y-4 text-sm">
//               <div>
//                 <p className="text-xs text-slate-400 mb-1">Incident Type</p>
//                 <p className="font-semibold text-slate-800 capitalize">
//                   {complaint?.incidentType || "General Incident"}
//                 </p>
//               </div>
//               <div>
//                 <p className="text-xs text-slate-400 mb-1">Description (Original Statement)</p>
//                 <p className="text-slate-700 leading-relaxed bg-slate-50 rounded-lg p-3.5 border border-slate-100 whitespace-pre-wrap">
//                   {complaint?.description || "No statement recorded."}
//                 </p>
//               </div>
//               <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
//                 <div>
//                   <p className="text-xs text-slate-400 mb-1">Complainant Contact</p>
//                   <p className="font-medium text-slate-800">{complainantContact}</p>
//                   <p className="text-xs text-slate-500">{complainantEmail}</p>
//                 </div>
//                 <div>
//                   <p className="text-xs text-slate-400 mb-1">Location Details</p>
//                   <p className="font-medium text-slate-800">{complaint?.location || "Delhi"}</p>
//                 </div>
//               </div>
//               {complaint?.evidence && complaint.evidence.length > 0 && (
//                 <div>
//                   <p className="text-xs text-slate-400 mb-1">Attached Evidence</p>
//                   <div className="flex flex-wrap gap-2">
//                     {complaint.evidence.map((f, idx) => (
//                       <span
//                         key={idx}
//                         className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1.5 rounded-md border border-slate-200"
//                       >
//                         📎 {f}
//                       </span>
//                     ))}
//                   </div>
//                 </div>
//               )}
//             </div>
//           </div>
//         )}

//         {/* Tab: Legal Section Assistance */}
//         {activeTab === "legal" && (
//           <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
//             <h2 className="font-bold text-slate-900 mb-1">AI-Suggested Legal Sections</h2>
//             <p className="text-xs text-slate-500 mb-5">
//               Review each suggestion and accept the ones applicable to this case.
//             </p>
//             <div className="space-y-3">
//               {suggestedSections.map((s) => {
//                 const accepted = acceptedSections.includes(s.section);
//                 return (
//                   <div
//                     key={s.section}
//                     className={`border rounded-xl p-4 transition ${
//                       accepted ? "border-blue-700 bg-blue-50/40" : "border-slate-200"
//                     }`}
//                   >
//                     <div className="flex items-start justify-between gap-3 mb-2">
//                       <div>
//                         <p className="font-bold text-slate-900 text-sm">{s.section}</p>
//                         <p className="text-xs text-slate-500">{s.title}</p>
//                       </div>
//                       <div className="flex items-center gap-2 flex-shrink-0">
//                         <span className="text-xs font-semibold text-slate-500">{s.confidence}% match</span>
//                         <button
//                           onClick={() => toggleSection(s.section)}
//                           className={`w-7 h-7 rounded-full flex items-center justify-center transition cursor-pointer ${
//                             accepted ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-400"
//                           }`}
//                         >
//                           <Check size={14} strokeWidth={3} />
//                         </button>
//                       </div>
//                     </div>
//                     <p className="text-xs text-slate-500 leading-relaxed">{s.reasoning}</p>
//                   </div>
//                 );
//               })}
//             </div>
//           </div>
//         )}

//         {/* Tab: FIR Draft */}
//         {activeTab === "draft" && (
//           <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
//             <div className="flex items-center justify-between mb-4">
//               <div>
//                 <h2 className="font-bold text-slate-900">AI-Generated FIR Statement</h2>
//                 <p className="text-xs text-slate-500">
//                   Editable FIR draft synchronized with live MongoDB complaint details.
//                 </p>
//               </div>
//             </div>
//             <textarea
//               value={firDraft}
//               onChange={(e) => setFirDraft(e.target.value)}
//               rows={16}
//               className="w-full border border-slate-300 rounded-xl px-4 py-3 text-sm font-mono leading-relaxed focus:outline-none focus:ring-2 focus:ring-blue-700 resize-none"
//             />

//             <div className="flex flex-col sm:flex-row gap-3 mt-5">
//               <button
//                 onClick={() => handleStatusChange("FIR_DRAFT_GENERATED")}
//                 disabled={updatingStatus}
//                 className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl py-3 text-sm font-semibold transition cursor-pointer"
//               >
//                 Mark as FIR Drafted
//               </button>
//               <button
//                 onClick={() => handleStatusChange("FIR_REGISTERED")}
//                 disabled={updatingStatus}
//                 className="flex-1 bg-blue-950 hover:bg-blue-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer"
//               >
//                 <ShieldCheck size={16} />
//                 Verify & Register FIR
//               </button>
//               <button
//                 onClick={() => handleStatusChange("CLOSED")}
//                 disabled={updatingStatus}
//                 className="flex-1 bg-emerald-800 hover:bg-emerald-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer"
//               >
//                 <CheckCircle2 size={16} />
//                 Close Case
//               </button>
//             </div>
//           </div>
//         )}
//       </div>
//     </div>
//   );
// }

import { useNavigate, useParams } from "react-router";
import { useState, useEffect } from "react";
import {
  ArrowLeft,
  User,
  MapPin,
  Calendar,
  Package,
  FileText,
  Scale,
  Sparkles,
  Check,
  ShieldCheck,
  RefreshCw,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import { useTranslation } from "react-i18next";
import { fetchComplaintById, updateComplaintStatusApi, type Complaint } from "../../services/api";

const statusStyles: Record<string, string> = {
  SUBMITTED: "bg-slate-100 text-slate-700 border-slate-200",
  Submitted: "bg-slate-100 text-slate-700 border-slate-200",
  UNDER_REVIEW: "bg-blue-100 text-blue-800 border-blue-200",
  "Under Review": "bg-blue-100 text-blue-800 border-blue-200",
  INVESTIGATING: "bg-blue-100 text-blue-800 border-blue-200",
  ASSIGNED: "bg-blue-100 text-blue-800 border-blue-200",
  FIR_DRAFT_GENERATED: "bg-amber-100 text-amber-800 border-amber-200",
  "FIR Drafted": "bg-amber-100 text-amber-800 border-amber-200",
  "FIR Draft Generated": "bg-amber-100 text-amber-800 border-amber-200",
  OFFICER_VERIFICATION: "bg-orange-100 text-orange-800 border-orange-200",
  "Officer Verification": "bg-orange-100 text-orange-800 border-orange-200",
  FIR_REGISTERED: "bg-green-100 text-green-800 border-green-200",
  "FIR Registered": "bg-green-100 text-green-800 border-green-200",
  CLOSED: "bg-emerald-100 text-emerald-800 border-emerald-200",
  Closed: "bg-emerald-100 text-emerald-800 border-emerald-200",
  RESOLVED: "bg-emerald-100 text-emerald-800 border-emerald-200",
};

export default function ComplaintDetail() {
  const navigate = useNavigate();
  const { t } = useTranslation();
  const { id } = useParams<{ id: string }>();

  const [complaint, setComplaint] = useState<Complaint | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  const [activeTab, setActiveTab] = useState<"structured" | "legal" | "draft">("structured");
  const [acceptedSections, setAcceptedSections] = useState<string[]>(["IPC Section 379 / BNS 303"]);
  const [firDraft, setFirDraft] = useState("");

  const loadComplaint = async () => {
    if (!id) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetchComplaintById(id);
      if (res.complaint) {
        setComplaint(res.complaint);
        const c = res.complaint;
        const complainantName =
          c.victimName || c.victim?.name || (c.user && typeof c.user === "object" ? c.user.name : "Complainant");
        const complainantContact =
          c.victim?.contact || c.victim?.phone || (c.user && typeof c.user === "object" ? c.user.phone : "Not provided");

        setFirDraft(
          `FIRST INFORMATION REPORT\n\nComplaint ID: ${c.complaintId}\nDate of Incident: ${c.date || "Unspecified"}, Time: ${c.time || "Unspecified"}\nPlace of Occurrence: ${c.location || "Unspecified"}\n\nComplainant: ${complainantName}\nContact: ${complainantContact}\n\nIncident Category: ${c.incidentType || "General Incident"}\n\nBrief Facts of the Case:\n${c.description || "No statement recorded."}\n\nApplicable Legal Sections:\n- IPC Section 379 / Bharatiya Nyaya Sanhita (BNS)\n\nStatus: ${c.status}\n\nThis FIR draft has been auto-generated by NyayaySetu AI and verified by Delhi Police.`
        );
      }
    } catch (err: any) {
      console.error("Error loading complaint:", err);
      setError(err?.message || t("complaintDetail.loadError"));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadComplaint();
  }, [id]);

  const handleStatusChange = async (newStatus: string) => {
    if (!id) return;
    setUpdatingStatus(true);
    setError(null);
    setSuccessMessage(null);
    try {
      const res = await updateComplaintStatusApi(id, newStatus);
      if (res.complaint) {
        setComplaint(res.complaint);
        setSuccessMessage(t("complaintDetail.statusUpdatedTo").replace("{status}", newStatus.replace(/_/g, " ")));
        setTimeout(() => setSuccessMessage(null), 4000);
      }
    } catch (err: any) {
      console.error("Failed to update status:", err);
      setError(err?.message || t("complaintDetail.updateError"));
    } finally {
      setUpdatingStatus(false);
    }
  };

  const toggleSection = (section: string) => {
    setAcceptedSections((prev) => (prev.includes(section) ? prev.filter((s) => s !== section) : [...prev, section]));
  };

  if (loading && !complaint) {
    return (
      <div className="min-h-screen bg-slate-100 flex items-center justify-center p-4">
        <div className="bg-white border border-slate-200 rounded-2xl p-8 text-center shadow-xs">
          <RefreshCw className="animate-spin text-blue-800 mx-auto mb-3" size={28} />
          <p className="text-sm font-semibold text-slate-700">{t("complaintDetail.loadingRecord")}</p>
        </div>
      </div>
    );
  }

  const complainantName =
    complaint?.victimName ||
    complaint?.victim?.name ||
    (complaint?.user && typeof complaint.user === "object" ? complaint.user.name : null) ||
    t("complaintDetail.defaultComplainant");
  const complainantContact =
    complaint?.victim?.contact ||
    complaint?.victim?.phone ||
    (complaint?.user && typeof complaint.user === "object" ? complaint.user.phone : null) ||
    t("complaintDetail.notProvided");
  const complainantEmail =
    (complaint?.user && typeof complaint.user === "object" ? complaint.user.email : null) ||
    complaint?.victim?.email ||
    t("complaintDetail.notProvided");
  const displayDate =
    complaint?.date ||
    (complaint?.createdAt
      ? new Date(complaint.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })
      : t("trackFir.notSpecified"));

  const suggestedSections = [
    {
      section: "IPC Section 379 / BNS Section 303",
      title: t("complaintDetail.sectionTheftTitle"),
      confidence: 94,
      reasoning: t("complaintDetail.sectionTheftReasoning").replace("{incidentType}", complaint?.incidentType || "theft"),
    },
    {
      section: "IPC Section 356 / BNS Section 304",
      title: t("complaintDetail.sectionAssaultTitle"),
      confidence: 65,
      reasoning: t("complaintDetail.sectionAssaultReasoning"),
    },
  ];

  return (
    <div className="min-h-screen bg-slate-100 px-4 py-8">
      <div className="w-full max-w-5xl mx-auto">
        <div className="flex items-center justify-between mb-5">
          <button
            onClick={() => navigate("/police/complaints")}
            className="flex items-center gap-2 text-slate-500 hover:text-slate-800 text-sm font-medium transition cursor-pointer"
          >
            <ArrowLeft size={18} />
            {t("complaintDetail.backToComplaints")}
          </button>
          <button
            onClick={loadComplaint}
            title={t("complaintDetail.refreshRecordTitle")}
            className="flex items-center gap-1.5 text-xs text-slate-600 bg-white border border-slate-300 rounded-lg px-3 py-1.5 shadow-xs hover:bg-slate-50 transition cursor-pointer"
          >
            <RefreshCw size={13} className={loading ? "animate-spin" : ""} />
            {t("policeManageComplaints.refresh")}
          </button>
        </div>

        {successMessage && (
          <div className="bg-green-50 border border-green-200 text-green-800 text-xs rounded-xl p-3.5 mb-4 flex items-center gap-2 shadow-xs">
            <CheckCircle2 size={16} className="flex-shrink-0 text-green-600" />
            <span className="font-medium">{successMessage}</span>
          </div>
        )}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-800 text-xs rounded-xl p-3.5 mb-4 flex items-center gap-2 shadow-xs">
            <AlertCircle size={16} className="flex-shrink-0 text-red-600" />
            <span className="font-medium">{error}</span>
          </div>
        )}

        <div className="bg-white border border-slate-200 rounded-2xl p-6 mb-5 shadow-xs">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-5 pb-4 border-b border-slate-100">
            <div>
              <p className="text-xs text-slate-400 font-semibold uppercase tracking-wider">
                {t("complaintDetail.headerLabel")}
              </p>
              <h1 className="text-2xl font-bold text-slate-900 font-mono mt-0.5">{complaint?.complaintId || id}</h1>
            </div>

            <div className="flex items-center gap-3 bg-slate-50 p-2.5 rounded-xl border border-slate-200">
              <span className="text-xs font-semibold text-slate-600">{t("complaintDetail.statusLabel")}:</span>
              <select
                value={complaint?.status || "SUBMITTED"}
                onChange={(e) => handleStatusChange(e.target.value)}
                disabled={updatingStatus}
                className="border border-slate-300 rounded-lg px-3 py-1.5 text-xs font-bold text-slate-800 bg-white focus:ring-2 focus:ring-blue-700 outline-none cursor-pointer"
              >
                <option value="SUBMITTED">{t("myComplaints.statusSubmitted")}</option>
                <option value="UNDER_REVIEW">{t("myComplaints.statusUnderReview")}</option>
                <option value="FIR_DRAFT_GENERATED">{t("policeManageComplaints.filterFirDrafted")}</option>
                <option value="OFFICER_VERIFICATION">{t("myComplaints.statusOfficerVerification")}</option>
                <option value="FIR_REGISTERED">{t("myComplaints.statusFirRegistered")}</option>
                <option value="CLOSED">{t("myComplaints.statusClosed")}</option>
              </select>
              <span
                className={`text-[11px] font-bold px-2.5 py-1 rounded-full border ${
                  statusStyles[complaint?.status || "SUBMITTED"] || "bg-slate-100 text-slate-700"
                }`}
              >
                {(complaint?.status || "SUBMITTED").replace(/_/g, " ")}
              </span>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 text-sm bg-slate-50 rounded-xl p-4">
            <div className="flex items-start gap-2">
              <User size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">{t("trackFir.complainant")}</p>
                <p className="font-medium text-slate-800">{complainantName}</p>
                <p className="text-[11px] text-slate-500">{complainantContact}</p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Calendar size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">{t("complaintDetail.dateAndTime")}</p>
                <p className="font-medium text-slate-800">
                  {displayDate}
                  {complaint?.time ? `, ${complaint.time}` : ""}
                </p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <MapPin size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">{t("trackFir.location")}</p>
                <p className="font-medium text-slate-800">{complaint?.location || "Delhi"}</p>
              </div>
            </div>
            <div className="flex items-start gap-2">
              <Package size={15} className="text-slate-400 mt-0.5" />
              <div>
                <p className="text-xs text-slate-400">{t("complaintDetail.categoryAndProperty")}</p>
                <p className="font-medium text-slate-800 capitalize">{complaint?.incidentType || t("dashboard.genericIncident")}</p>
                {complaint?.stolenItem && (
                  <p className="text-[11px] text-slate-500">{t("myComplaints.stolenLabel")}: {complaint.stolenItem}</p>
                )}
              </div>
            </div>
          </div>
        </div>

        <div className="flex bg-white border border-slate-200 rounded-xl p-1.5 mb-5 shadow-xs">
          {[
            { key: "structured", label: t("complaintDetail.tabStructured"), icon: FileText },
            { key: "legal", label: t("complaintDetail.tabLegal"), icon: Scale },
            { key: "draft", label: t("complaintDetail.tabDraft"), icon: Sparkles },
          ].map((tab) => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as typeof activeTab)}
              className={`flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-semibold rounded-lg transition cursor-pointer ${
                activeTab === tab.key ? "bg-blue-950 text-white" : "text-slate-500 hover:bg-slate-50"
              }`}
            >
              <tab.icon size={15} />
              {tab.label}
            </button>
          ))}
        </div>

        {activeTab === "structured" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <h2 className="font-bold text-slate-900 mb-4">{t("complaintDetail.aiStructuredTitle")}</h2>
            <div className="space-y-4 text-sm">
              <div>
                <p className="text-xs text-slate-400 mb-1">{t("dashboard.genericIncident")} {t("complaintDetail.typeSuffix")}</p>
                <p className="font-semibold text-slate-800 capitalize">{complaint?.incidentType || t("dashboard.genericIncident")}</p>
              </div>
              <div>
                <p className="text-xs text-slate-400 mb-1">{t("complaintDetail.descriptionLabel")}</p>
                <p className="text-slate-700 leading-relaxed bg-slate-50 rounded-lg p-3.5 border border-slate-100 whitespace-pre-wrap">
                  {complaint?.description || t("trackFir.noStatement")}
                </p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <p className="text-xs text-slate-400 mb-1">{t("complaintDetail.complainantContact")}</p>
                  <p className="font-medium text-slate-800">{complainantContact}</p>
                  <p className="text-xs text-slate-500">{complainantEmail}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-400 mb-1">{t("complaintDetail.locationDetails")}</p>
                  <p className="font-medium text-slate-800">{complaint?.location || "Delhi"}</p>
                </div>
              </div>
              {complaint?.evidence && complaint.evidence.length > 0 && (
                <div>
                  <p className="text-xs text-slate-400 mb-1">{t("complaintDetail.attachedEvidence")}</p>
                  <div className="flex flex-wrap gap-2">
                    {complaint.evidence.map((f, idx) => (
                      <span key={idx} className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1.5 rounded-md border border-slate-200">
                        📎 {f}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {activeTab === "legal" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <h2 className="font-bold text-slate-900 mb-1">{t("complaintDetail.aiSuggestedSections")}</h2>
            <p className="text-xs text-slate-500 mb-5">{t("complaintDetail.legalSubtitle")}</p>
            <div className="space-y-3">
              {suggestedSections.map((s) => {
                const accepted = acceptedSections.includes(s.section);
                return (
                  <div key={s.section} className={`border rounded-xl p-4 transition ${accepted ? "border-blue-700 bg-blue-50/40" : "border-slate-200"}`}>
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div>
                        <p className="font-bold text-slate-900 text-sm">{s.section}</p>
                        <p className="text-xs text-slate-500">{s.title}</p>
                      </div>
                      <div className="flex items-center gap-2 flex-shrink-0">
                        <span className="text-xs font-semibold text-slate-500">{s.confidence}% {t("complaintDetail.match")}</span>
                        <button
                          onClick={() => toggleSection(s.section)}
                          className={`w-7 h-7 rounded-full flex items-center justify-center transition cursor-pointer ${
                            accepted ? "bg-blue-700 text-white" : "bg-slate-100 text-slate-400"
                          }`}
                        >
                          <Check size={14} strokeWidth={3} />
                        </button>
                      </div>
                    </div>
                    <p className="text-xs text-slate-500 leading-relaxed">{s.reasoning}</p>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {activeTab === "draft" && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h2 className="font-bold text-slate-900">{t("complaintDetail.aiGeneratedFir")}</h2>
                <p className="text-xs text-slate-500">{t("complaintDetail.draftSubtitle")}</p>
              </div>
            </div>
            <textarea
              value={firDraft}
              onChange={(e) => setFirDraft(e.target.value)}
              rows={16}
              className="w-full border border-slate-300 rounded-xl px-4 py-3 text-sm font-mono leading-relaxed focus:outline-none focus:ring-2 focus:ring-blue-700 resize-none"
            />

            <div className="flex flex-col sm:flex-row gap-3 mt-5">
              <button
                onClick={() => handleStatusChange("FIR_DRAFT_GENERATED")}
                disabled={updatingStatus}
                className="flex-1 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl py-3 text-sm font-semibold transition cursor-pointer"
              >
                {t("complaintDetail.markAsFirDrafted")}
              </button>
              <button
                onClick={() => handleStatusChange("FIR_REGISTERED")}
                disabled={updatingStatus}
                className="flex-1 bg-blue-950 hover:bg-blue-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer"
              >
                <ShieldCheck size={16} />
                {t("complaintDetail.verifyAndRegister")}
              </button>
              <button
                onClick={() => handleStatusChange("CLOSED")}
                disabled={updatingStatus}
                className="flex-1 bg-emerald-800 hover:bg-emerald-900 text-white rounded-xl py-3 text-sm font-semibold transition flex items-center justify-center gap-2 cursor-pointer"
              >
                <CheckCircle2 size={16} />
                {t("complaintDetail.closeCase")}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}